const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('rjc', {
  getState: () => ipcRenderer.invoke('state:get'),
  updateConfig: (partial) => ipcRenderer.invoke('config:update', partial),
  tune: (args) => ipcRenderer.invoke('tv:tune', args),
  power: (args) => ipcRenderer.invoke('tv:power', args),
  identify: (args) => ipcRenderer.invoke('tv:identify', args),
  scan: () => ipcRenderer.invoke('net:scan'),
  vizioPairStart: (args) => ipcRenderer.invoke('vizio:pairStart', args),
  vizioPairPin: (args) => ipcRenderer.invoke('vizio:pairPin', args),
  vizioUnpair: (args) => ipcRenderer.invoke('vizio:unpair', args),
  vizioVol: (args) => ipcRenderer.invoke('vizio:vol', args),
  vizioPower: (args) => ipcRenderer.invoke('vizio:power', args),
  vizioScan: () => ipcRenderer.invoke('vizio:scan'),
  audioSet: (args) => ipcRenderer.invoke('audio:set', args),
  audioMute: (args) => ipcRenderer.invoke('audio:mute', args),
  toggleFullscreen: () => ipcRenderer.invoke('win:fullscreen'),
  isFullscreen: () => ipcRenderer.invoke('win:isFullscreen'),
  setOverlay: (args) => ipcRenderer.invoke('win:overlay', args),
  diagInfo: () => ipcRenderer.invoke('diag:info'),
  diagPing: (args) => ipcRenderer.invoke('diag:ping', args),
  diagTcp: (args) => ipcRenderer.invoke('diag:tcp', args),
  diagItach: (args) => ipcRenderer.invoke('diag:itach', args),
  diagComports: () => ipcRenderer.invoke('diag:comports'),
  logGet: () => ipcRenderer.invoke('log:get'),
  logAdd: (args) => ipcRenderer.invoke('log:add', args),
  logClear: () => ipcRenderer.invoke('log:clear'),
  logExport: () => ipcRenderer.invoke('log:export'),
  configExport: () => ipcRenderer.invoke('config:export'),
  configImport: () => ipcRenderer.invoke('config:import'),
  configOpenFolder: () => ipcRenderer.invoke('config:openFolder'),
  configReset: () => ipcRenderer.invoke('config:reset'),
  onLog: (cb) => ipcRenderer.on('log', (_e, entry) => cb(entry)),
  onStatus: (cb) => ipcRenderer.on('status', (_e, m) => cb(m)),
  onConfig: (cb) => ipcRenderer.on('config', (_e, c) => cb(c)),
  onScanProgress: (cb) => ipcRenderer.on('scan:progress', (_e, p) => cb(p)),
});
